name: otel_anasayfa
description: "Otel ana sayfa Flutter UI"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
